# Generated by Django 3.1 on 2020-08-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='risk',
            field=models.BooleanField(default=False),
        ),
    ]
