# Generated by Django 3.1 on 2020-08-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_member_risk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('temperature', models.IntegerField()),
                ('current_symptoms', models.CharField(max_length=100)),
                ('previous_diseases', models.CharField(max_length=100)),
                ('travel', models.BooleanField(default=False)),
                ('social_distance', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
