# Generated by Django 3.1 on 2020-09-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0007_remove_person_collegeid'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=12)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('result', models.BooleanField(default=False)),
            ],
        ),
    ]
