# Generated by Django 3.1 on 2020-09-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0008_testdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdetails',
            name='timestamp',
            field=models.DateField(auto_now_add=True),
        ),
    ]
