# Generated by Django 3.1 on 2020-09-24 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0009_auto_20200924_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdetails',
            name='timestamp',
            field=models.DateField(default=datetime.date(2020, 9, 24)),
        ),
    ]
