# Generated by Django 3.1 on 2020-09-24 10:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0010_auto_20200924_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdetails',
            name='timestamp',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
