# Generated by Django 3.1 on 2020-09-24 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0012_testdetails_test_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testdetails',
            name='test_file',
        ),
    ]
