# Generated by Django 3.1 on 2020-09-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0014_testdetails_test_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdetails',
            name='test_file',
            field=models.FileField(blank=True, null=True, upload_to='test-records/'),
        ),
    ]
